//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalResourcesLibrary.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_FifthSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FifthSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два года по приказу Екатерины II в Гродно жил под стражей король польский Станислав Август Понятовский. В 1795 году в Новом замке он подписал акт отречения от престола, остановив 200-летнее существование Речи Посполитой..
        /// </summary>
        public static string Home_Index_FifthSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FifthSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_FirstSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FirstSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гродно - уникальный город Беларуси с выдающимися памятниками зодчества прошлого: Коложская церковь, Фарный, Бригитский, Францисканский костелы и монастыри, церковь Рождества Богородицы..
        /// </summary>
        public static string Home_Index_FirstSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FirstSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_FourthSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FourthSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При великом литовском князе Витовте, королях польских Стефане Батории, Станиславе Понятовском Гродно являлся резиденцией монарха и  фактически был приравнен к столицам Вильнюсу и Варшаве..
        /// </summary>
        public static string Home_Index_FourthSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FourthSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крестоносцы, когда ходили на Гродненщину, нередко говорили: «Идем на пущу»..
        /// </summary>
        public static string Home_Index_SecondSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_SecondSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Появление в гербе Гродно оленя связано с одним из основных занятий горожан - охотой. Крестоносцы, когда ходили на Гродненщину, нередко говорили: «Идем на пущу»..
        /// </summary>
        public static string Home_Index_SecondSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_SecondSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_SixthSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_SixthSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два года по приказу Екатерины II в Гродно жил под стражей король польский Станислав Август Понятовский. В 1795 году в Новом замке он подписал акт отречения от престола, остановив 200-летнее существование Речи Посполитой..
        /// </summary>
        public static string Home_Index_SixthSlide_Title1 {
            get {
                return ResourceManager.GetString("Home_Index_SixthSlide_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_ThirdSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_ThirdSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прошлое Гродно уходит в дымку веков - в первой трети XII в. - раньше, чем восточноевропейские столицы Москва и Вильнюс, – упоминается в летописях..
        /// </summary>
        public static string Home_Index_ThirdSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_ThirdSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Archive.
        /// </summary>
        public static string LeftPanel_All_Archive {
            get {
                return ResourceManager.GetString("LeftPanel_All_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents satisfying the search not found.
        /// </summary>
        public static string Search_Documents_Not_Fount {
            get {
                return ResourceManager.GetString("Search_Documents_Not_Fount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on.
        /// </summary>
        public static string Search_PostedDate {
            get {
                return ResourceManager.GetString("Search_PostedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string Shared_Error_Body {
            get {
                return ResourceManager.GetString("Shared_Error_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string Shared_Error_Title {
            get {
                return ResourceManager.GetString("Shared_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; {0} The Library Grodno..
        /// </summary>
        public static string Shared_Layout_Site_Copyright {
            get {
                return ResourceManager.GetString("Shared_Layout_Site_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Shared_Menu_About {
            get {
                return ResourceManager.GetString("Shared_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string Shared_Menu_AdvancedSearch {
            get {
                return ResourceManager.GetString("Shared_Menu_AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shared_Menu_Home {
            get {
                return ResourceManager.GetString("Shared_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Shared_Menu_Search {
            get {
                return ResourceManager.GetString("Shared_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Shared_Template_Archives_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Archives_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Shared_Template_Categories_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Shared_Template_Tags_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Site_Button_Download {
            get {
                return ResourceManager.GetString("Site_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://librarygrodno.apphb.com.
        /// </summary>
        public static string Site_Domen {
            get {
                return ResourceManager.GetString("Site_Domen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Grodno.
        /// </summary>
        public static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grodno - Information for all.
        /// </summary>
        public static string Site_Name_Body {
            get {
                return ResourceManager.GetString("Site_Name_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Library.
        /// </summary>
        public static string Site_Name_Header {
            get {
                return ResourceManager.GetString("Site_Name_Header", resourceCulture);
            }
        }
    }
}
