//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalResourcesLibrary.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being accepted for the cause, get a grip with the spirit..
        /// </summary>
        public static string Home_Index_FirstSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FirstSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Slide.
        /// </summary>
        public static string Home_Index_FirstSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FirstSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock time is measured, and the time of human life, but than, say, you will measure the depth of the Eastern Ocean?.
        /// </summary>
        public static string Home_Index_SecondSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_SecondSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Slide.
        /// </summary>
        public static string Home_Index_SecondSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_SecondSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many things we do not understand, not because our concepts are weak, but because these things do not fall within the scope of our concepts..
        /// </summary>
        public static string Home_Index_ThirdSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_ThirdSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Slide.
        /// </summary>
        public static string Home_Index_ThirdSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_ThirdSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents satisfying the search not found.
        /// </summary>
        public static string Search_Documents_Not_Fount {
            get {
                return ResourceManager.GetString("Search_Documents_Not_Fount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on.
        /// </summary>
        public static string Search_PostedDate {
            get {
                return ResourceManager.GetString("Search_PostedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string Shared_Error_Body {
            get {
                return ResourceManager.GetString("Shared_Error_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string Shared_Error_Title {
            get {
                return ResourceManager.GetString("Shared_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy; {0} The Library Grodno..
        /// </summary>
        public static string Shared_Layout_Site_Copyright {
            get {
                return ResourceManager.GetString("Shared_Layout_Site_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Shared_Menu_About {
            get {
                return ResourceManager.GetString("Shared_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shared_Menu_Home {
            get {
                return ResourceManager.GetString("Shared_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Shared_Menu_Search {
            get {
                return ResourceManager.GetString("Shared_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Shared_Template_Archives_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Archives_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Shared_Template_Categories_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://librarygrodno.apphb.com.
        /// </summary>
        public static string Site_Domen {
            get {
                return ResourceManager.GetString("Site_Domen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Grodno.
        /// </summary>
        public static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
    }
}
