//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalResourcesLibrary.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document.
        /// </summary>
        public static string Add_Cookie_Document {
            get {
                return ResourceManager.GetString("Add_Cookie_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BookmarksModelWindow_Add {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add stuff - &quot;.
        /// </summary>
        public static string BookmarksModelWindow_Add_Body_One {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Add_Body_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; to bookmarks.
        /// </summary>
        public static string BookmarksModelWindow_Add_Body_Two {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Add_Body_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding material to your bookmarks.
        /// </summary>
        public static string BookmarksModelWindow_Add_Title {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BookmarksModelWindow_Cancel {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BookmarksModelWindow_Remove {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to remove the material - &quot;.
        /// </summary>
        public static string BookmarksModelWindow_Remove_Body_One {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Remove_Body_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; of the tabs.
        /// </summary>
        public static string BookmarksModelWindow_Remove_Body_Two {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Remove_Body_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing from favorites.
        /// </summary>
        public static string BookmarksModelWindow_Remove_Title {
            get {
                return ResourceManager.GetString("BookmarksModelWindow_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string Delete_Cookie_Document {
            get {
                return ResourceManager.GetString("Delete_Cookie_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents_Type {
            get {
                return ResourceManager.GetString("Documents_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;/Content/themes/images/About/1.jpg&quot; class=&quot;about-image&quot; alt=&quot;Гродно – город церквей и костёлов&quot;&gt;
        ///        &lt;p&gt;
        ///            Гродно – город церквей и костёлов, старых замков и дворцов королей. Древняя история Гродно начиналась с Замковой горы. На высоком холме, в устье рек Немана и Городничанки в Х-ХI веках было заложено укрепленное поселение. В 1127 году город впервые упоминается в письменных источниках.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            История отвела этому городу необычное место в решении с [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_About_Body {
            get {
                return ResourceManager.GetString("Home_About_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_FifthSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FifthSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Polish king Stanislaw August Poniatowski lived in Grodno for two years upon detention by the order of Catherine II. In 1795, in New Castle, he signed the act of abdication, stopping 200 - year existence of the Commonwealth..
        /// </summary>
        public static string Home_Index_FifthSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FifthSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_FirstSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FirstSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grodno is a unique town in Belarus with outstanding architectural monuments of the past: Kalozha Church;  Farny, Bridgettine and Franciscan catholic churches and monasteries and  the Church of Saint Mother of God..
        /// </summary>
        public static string Home_Index_FirstSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FirstSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_FourthSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_FourthSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under the rule of thegreat Lithuanian Duke Vytautas andthe Kings of Poland Stefan and Stanislaw Poniatowski Grodno was the residence of the monarch, and in fact has been equal to such capitals as Vilnius and Warsaw..
        /// </summary>
        public static string Home_Index_FourthSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_FourthSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крестоносцы, когда ходили на Гродненщину, нередко говорили: «Идем на пущу»..
        /// </summary>
        public static string Home_Index_SecondSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_SecondSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A deer on the emblem of Grodno is associated with the main occupation of townspeople – hunting. Crusaders, when they were conducting campaigns to Grodno region, often said: “We are going to the forest”..
        /// </summary>
        public static string Home_Index_SecondSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_SecondSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the efforts of the French physician and biologist Zh.E.Zhiliber obstetric and Veterinary School, Clinical Hospital and the Botanical Garden of the two thousand plants were established in Grodno in the second half of the XVIII century..
        /// </summary>
        public static string Home_Index_SeventhSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_SeventhSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_SixthSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_SixthSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The period of prosperity in Grodno in the second half of the XVIII century is associated with the name of Anthony Tizengauz, the mayor of the city. Weaving, manufacture of bed linen, furniture, glass, tobacco, metals, leather goods and weapons were developing..
        /// </summary>
        public static string Home_Index_SixthSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_SixthSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Home_Index_ThirdSlide_Body {
            get {
                return ResourceManager.GetString("Home_Index_ThirdSlide_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The past of Grodno goes into the haze of centuries. Grodno was mentioned in the chronicles in the first third of the XII century, earlier than Eastern European capitals Moscow and Vilnius..
        /// </summary>
        public static string Home_Index_ThirdSlide_Title {
            get {
                return ResourceManager.GetString("Home_Index_ThirdSlide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Archive.
        /// </summary>
        public static string LeftPanel_All_Archive {
            get {
                return ResourceManager.GetString("LeftPanel_All_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_AdvancedSearch_AutoComplete {
            get {
                return ResourceManager.GetString("Search_AdvancedSearch_AutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents satisfying the search not found.
        /// </summary>
        public static string Search_Documents_Not_Fount {
            get {
                return ResourceManager.GetString("Search_Documents_Not_Fount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on.
        /// </summary>
        public static string Search_PostedDate {
            get {
                return ResourceManager.GetString("Search_PostedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string Shared_Error_Body {
            get {
                return ResourceManager.GetString("Shared_Error_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string Shared_Error_Title {
            get {
                return ResourceManager.GetString("Shared_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright &amp;copy;.
        /// </summary>
        public static string Shared_Layout_Site_Copyright {
            get {
                return ResourceManager.GetString("Shared_Layout_Site_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Shared_Menu_About {
            get {
                return ResourceManager.GetString("Shared_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string Shared_Menu_AdvancedSearch {
            get {
                return ResourceManager.GetString("Shared_Menu_AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shared_Menu_Home {
            get {
                return ResourceManager.GetString("Shared_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Advanced Search.
        /// </summary>
        public static string Shared_Menu_Result_AdvancedSearch {
            get {
                return ResourceManager.GetString("Shared_Menu_Result_AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Shared_Menu_Search {
            get {
                return ResourceManager.GetString("Shared_Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Shared_Template_Archives_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Archives_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Shared_Template_Categories_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Categories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Shared_Template_Tags_Title {
            get {
                return ResourceManager.GetString("Shared_Template_Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Site_Button_Download {
            get {
                return ResourceManager.GetString("Site_Button_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://librarygrodno.apphb.com.
        /// </summary>
        public static string Site_Domen {
            get {
                return ResourceManager.GetString("Site_Domen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Grodno.
        /// </summary>
        public static string Site_Name {
            get {
                return ResourceManager.GetString("Site_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grodno - Information for all.
        /// </summary>
        public static string Site_Name_Body {
            get {
                return ResourceManager.GetString("Site_Name_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Library.
        /// </summary>
        public static string Site_Name_Header {
            get {
                return ResourceManager.GetString("Site_Name_Header", resourceCulture);
            }
        }
    }
}
