//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlContext.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [DbConfigurationType(typeof(MySql.Data.Entity.MySqlEFConfiguration))]
    public partial class LibDbEntities : DbContext
    {
        public LibDbEntities()
            : base("name=LibDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<article> article { get; set; }
        public DbSet<articleloc> articleloc { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<categoryloc> categoryloc { get; set; }
        public DbSet<locale> locale { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<store> store { get; set; }
        public DbSet<storeloc> storeloc { get; set; }
        public DbSet<tag> tag { get; set; }
        public DbSet<tagloc> tagloc { get; set; }
        public DbSet<user> user { get; set; }
    }
}
