//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class locale
    {
        public locale()
        {
            this.articleloc = new HashSet<articleloc>();
            this.categoryloc = new HashSet<categoryloc>();
            this.storeloc = new HashSet<storeloc>();
            this.tagloc = new HashSet<tagloc>();
            this.typefile = new HashSet<typefile>();
        }
    
        public int id { get; set; }
        public string locale1 { get; set; }
        public string language { get; set; }
    
        public virtual ICollection<articleloc> articleloc { get; set; }
        public virtual ICollection<categoryloc> categoryloc { get; set; }
        public virtual ICollection<storeloc> storeloc { get; set; }
        public virtual ICollection<tagloc> tagloc { get; set; }
        public virtual ICollection<typefile> typefile { get; set; }
    }
}
