//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class searchindexlog
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsMain { get; set; }
        public bool IsDelta { get; set; }
    }
}
