//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalResourcesLibrary.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.article = new HashSet<article>();
            this.category1 = new HashSet<category>();
            this.categoryloc = new HashSet<categoryloc>();
            this.store = new HashSet<store>();
        }
    
        public long id { get; set; }
        public Nullable<long> parent { get; set; }
    
        public virtual ICollection<article> article { get; set; }
        public virtual ICollection<category> category1 { get; set; }
        public virtual category category2 { get; set; }
        public virtual ICollection<categoryloc> categoryloc { get; set; }
        public virtual ICollection<store> store { get; set; }
    }
}
