//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalResourcesLibrary.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag
    {
        public tag()
        {
            this.tagloc = new HashSet<tagloc>();
            this.article = new HashSet<article>();
            this.store = new HashSet<store>();
        }
    
        public int id { get; set; }
        public string meta { get; set; }
    
        public virtual ICollection<tagloc> tagloc { get; set; }
        public virtual ICollection<article> article { get; set; }
        public virtual ICollection<store> store { get; set; }
    }
}
